// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxjywsoxsjoyvuzqxovk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4anl3c294c2pveXZ1enF4b3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3MDg1MDYsImV4cCI6MjA3OTI4NDUwNn0._yx1qQnDb0o4Bt3w_X4z7NBIHGYJ3wIELUyRI7h4Tss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});